// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2dmTBxGN8-ACoX5gwRJiV_FxGFdauZGY',
    appId: '1:785962378574:web:2a3d64cc4ad36b313b2a1f',
    messagingSenderId: '785962378574',
    projectId: 'flutterapp-b71e3',
    authDomain: 'flutterapp-b71e3.firebaseapp.com',
    storageBucket: 'flutterapp-b71e3.appspot.com',
    measurementId: 'G-NPVJNQ1P4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt5A-3NOMmuKTSSRN4fkf3yZbihNNowBk',
    appId: '1:785962378574:android:b339d0c95b7c79c63b2a1f',
    messagingSenderId: '785962378574',
    projectId: 'flutterapp-b71e3',
    storageBucket: 'flutterapp-b71e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAppQPgG0EJ4qvQoYXm7vh6uw-yPPaQ9iY',
    appId: '1:785962378574:ios:6cecf9d87527e6863b2a1f',
    messagingSenderId: '785962378574',
    projectId: 'flutterapp-b71e3',
    storageBucket: 'flutterapp-b71e3.appspot.com',
    iosClientId: '785962378574-mnat9ce9h4ogkaq7as2bd6nsrfjpnmnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAppQPgG0EJ4qvQoYXm7vh6uw-yPPaQ9iY',
    appId: '1:785962378574:ios:6cecf9d87527e6863b2a1f',
    messagingSenderId: '785962378574',
    projectId: 'flutterapp-b71e3',
    storageBucket: 'flutterapp-b71e3.appspot.com',
    iosClientId: '785962378574-mnat9ce9h4ogkaq7as2bd6nsrfjpnmnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMobile',
  );
}
